export const CATEGORIES = {
  'Motor': [
    'Légbeömlő',
    'Szívócső / fojtószelep',
    'Üzemanyagrendszer',
    'Gyújtás',
    'Kipufogó',
    'Vezérműtengely',
    'Szelepek',
    'Hengerűrtartalom',
    'Dugattyúk / kompresszor',
    'Olaj / Hűtés',
    'Lendkerék',
  ],
  'Futómű és kormánymű': [
    'Fékek',
    'Rugók',
    'Lengéscsillapítók',
    'Kanyarstabilizátor',
    'Futómű',
    'Kormánymű',
  ],
  'Hajtáslánc': [
    'Differenciálmű',
    'Sebességváltó',
    'Kuplung',
    'Hajtókarszelet',
  ],
  'Karosszéria': [
    'Karosszéria-készlet',
    'Szélesítőkészlet',
    'Első aerodinamika',
    'Hátsó aerodinamika',
    'Motorháztető',
    'Oldalszegélyzők',
    'Hátsó lökhárító',
  ],
  'Kerekek': [
    'Abroncsok',
    'Felnik',
    'Nyomtávszélesítés',
  ],
  'Teljesítmény': [
    'Motorcsere',
    'Hajtáslánc-csere',
    'Feltöltés',
    'Alvázszerkezet-megerősítés',
  ],
}

export const EFFECT_FIELDS = [
  { key: 'power_hp',               label: 'Power (LE)',            type: 'number', step: 1   },
  { key: 'torque_nm',              label: 'Torque (Nm)',           type: 'number', step: 1   },
  { key: 'weight_kg',              label: 'Weight change (kg)',    type: 'number', step: 1, hint: 'negative = lighter' },
  { key: 'braking_efficiency_pct', label: 'Braking efficiency %',  type: 'number', step: 0.1 },
  { key: 'stat_speed',             label: 'Stat: Speed',           type: 'number', step: 0.1 },
  { key: 'stat_handling',          label: 'Stat: Handling',        type: 'number', step: 0.1 },
  { key: 'stat_acceleration',      label: 'Stat: Acceleration',    type: 'number', step: 0.1 },
  { key: 'stat_launch',            label: 'Stat: Launch',          type: 'number', step: 0.1 },
  { key: 'stat_braking',           label: 'Stat: Braking',         type: 'number', step: 0.1 },
  { key: 'stat_offroad',           label: 'Stat: Offroad',         type: 'number', step: 0.1 },
  { key: 'unlocks_tuning',         label: 'Unlocks tuning sliders',type: 'bool'              },
  { key: 'unlock_type',            label: 'Unlock type',           type: 'select',
    options: ['','suspension','diff','arb','trans','all'] },
  { key: 'compound_type',          label: 'Compound type',         type: 'select',
    options: ['','Stock','Street','Sport','Semi-Slick','Race Slick','Rally','Drift','Off-Road'] },
]
